### ISSUE TITLE
请问模型的预测速度好慢是怎么回事

### ISSUE THREAD

**Issue by weikang-wang** [yuanxiaosc/Multiple-Relations-Extraction-Only-Look-Once#1]
如题

**Comment by yuanxiaosc** [comment]
@weikang-wang 
有两方面原因：
1. 输出的关系预测结果predicate_head_predictions 和 predicate_head_probabilities 维度比较大，每条数据的关系预测结果都是 128 x 128 x 50 （序列长度*序列长度*关系种类）。
2. 模型写文件数据是单进程的，跟不上模型预测输入速度。可以把run_multiple_relations_extraction.py 第884~914 行写文件改成TensorFlow的自带的写文件代码就会有速度提升。

因为模型现在的损失函数设计还存在问题，所有会输出 128 x 128 x 50 维度的关系预测结果便于检查，未来可能会直接输出 128*128 维度的关系预测结果，这样输出文件大小也就变小了。
