### ISSUE TITLE
请问这个模型，线下最好的成绩到多少呀

### ISSUE THREAD

**Issue by zhangatao** [yuanxiaosc/Multiple-Relations-Extraction-Only-Look-Once#2]
如题

**Comment by yuanxiaosc** [comment]
@zhangatao 这个模型代码还存在问题（比如损失函数），所有效果肯定不会太好，而且实验室的老CPU服务器6个训练周期并未跑完....如果你有条件运行模型，欢迎通过实验来确定模型成绩。
