### ISSUE TITLE
Raw data of baidu yun have invalid

### ISSUE THREAD

**Issue by BIGKUANG** [yuanxiaosc/Multiple-Relations-Extraction-Only-Look-Once#3]
I‘m a student， and have missed the registration. can send me a raw dataset. Thanks~~
email: 915320555@qq.com

**Comment by yuanxiaosc** [comment]
@BIGKUANG   Contact my mailbox wangzichaochaochao@gmail.com

**Comment by tantingting1012** [comment]
I have missed the registration，and the download link of the dataset you provided is invalid. Can you provide the dataset for the experiment again?. or can send me a raw dataset. Thanks~~
email: 1109773965@qq.com
