### ISSUE TITLE
Out of range: Read less bytes than requested

### ISSUE THREAD

**Issue by yzho0907** [yuanxiaosc/Multiple-Relations-Extraction-Only-Look-Once#6]
W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_v2_ops.cc:184 : Out of range: Read less bytes than requested
内存120G
cpu
请问下作者有遇到这个问题嘛？怎么解决呢？

**Comment by yuanxiaosc** [comment]
@yzho0907 内存不够用的情况下，最简单的方法就是减小batchsize，当然你还可以百度其它方法。第二，内存占用过大主要是因为输出的关系矩阵太大 句子最大长度x句子最大长度x关系数量 ，所有可以修改关系矩阵相关代码。

**Comment by yzho0907** [comment]
@yuanxiaosc 120G都不够嘛？请问下你们实验的时候内存是多少呢？

**Comment by yuanxiaosc** [comment]
@yzho0907 应该用不到120G，我们实验室多人共用一台157G的CPU服务器，上面同时跑了一堆程序。

**Comment by yzho0907** [comment]
@yuanxiaosc 应该不是内存的问题，我刚才试着调小的batch size或者是裁剪的数据集，都会报同样的错误.....很奇怪

**Comment by yuanxiaosc** [comment]
@yzho0907  你环境对不对哦，最好用tensorflow1.12 python3.6

**Comment by yzho0907** [comment]
(py36) young@young-ThinkPad-T450 ~ $ pip list | grep tensorflow
tensorflow              1.12.0  
环境都是一致的，这是我个人电脑；我们gpu服务器上也是同样的环境.....

**Comment by yzho0907** [comment]
bert预训练模型不完整导致的
