### ISSUE TITLE
do eval

### ISSUE THREAD

**Issue by ZTurboX** [yuanxiaosc/Multiple-Relations-Extraction-Only-Look-Once#8]
怎样设置model evaluation

**Comment by yuanxiaosc** [comment]
@zhentaoCoding https://github.com/yuanxiaosc/Entity-Relation-Extraction 可以参考这个里面的评估脚本

**Comment by shenliyan01** [comment]
我可不可以诺诺的问一句，这个加BERT的代码，也是使用ubuntu环境的吗？菜鸟一枚，还只会在win操作系统下搞。

**Comment by yuanxiaosc** [comment]
我没试过windows跑这个代码，不过应该都行，Python代码本来就是通用的

shenliyan01 <notifications@github.com> 于 2019年10月28日周一 下午9:46写道：
