### ISSUE TITLE
标签信息

### ISSUE THREAD

**Issue by ZTurboX** [yuanxiaosc/Multiple-Relations-Extraction-Only-Look-Once#9]
请问该方法中，做head prediction时，预测实体label embedding没有用到吗？例如将bert encoder输出和实体label embedding做拼接，然后作为head prediction的输入

**Comment by yuanxiaosc** [comment]
@zhentaoCoding 你可以直接认为本资源只是把 [Joint entity recognition and relation extraction as a multi-head selection problem](https://arxiv.org/abs/1804.07847) 这篇论文中的特征提取器LSTM-CRF换成了BERT，原理和细节都可以查看该论文。
